#!/usr/bin/env bash

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

if [[ -n $WAYLAND_DISPLAY ]]; then
	dmenu=dmenu-wl
	xdotool="ydotool type --file -"
elif [[ -n $DISPLAY ]]; then
	dmenu=dmenu
	xdotool="xdotool type --clearmodifiers --file -"
else
	echo "Error: No Wayland or X11 display detected" >&2
	exit 1
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )


password=$(printf '%s\n' "${password_files[@]}" | "$dmenu" "$@")


[[ -n $password ]] || exit


if [[ ! -f "$prefix/$password.gpg" ]]; then
	CHAR=$(echo -e "8\n10\n15\n20" | dmenu -p "How many characters to the new password")
	[[ -n $CHAR ]] || exit
	ECHAR=$(echo -e "Yes\nNo" | dmenu -p "Do you want spacial characters? ")
	[[ -n $ECHAR ]] || exit
	if [[ $ECHAR == 'No' ]]; then
		pass generate -c $password -n $CHAR && exit
	else
		pass generate -c $password $CHAR && exit
	fi
fi


if [[ $typeit -eq 0 ]]; then
	pass show -c "$password" 2>/dev/null
	echo $password
else
	pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } | $xdotool
fi
